USE PROJECT;
GO

DROP TABLE RECOMMENDATION;
DROP TABLE IS_ALLERGIC_TO;
DROP TABLE SURGERY;
DROP TABLE ALLERGY;
DROP TABLE DOSE;
DROP TABLE PRESCRIPTION;
DROP TABLE MEDICATION_CATALOG;
DROP TABLE LONG_TERM_ILLNESS;
DROP TABLE ILLNESS;
DROP TABLE ILLNESS_CATALOG;
DROP TABLE APPOINTMENT;
DROP TABLE MEDICAL_TEST;
DROP TABLE TEST_CATALOG;
DROP TABLE NURSE;
DROP TABLE DOCTOR;
DROP TABLE MEDICAL_HISTORY;
DROP TABLE PATIENT;

DELETE FROM RECOMMENDATION;
DELETE FROM IS_ALLERGIC_TO;
DELETE FROM SURGERY;
DELETE FROM ALLERGY;
DELETE FROM PATIENT;
DELETE FROM MEDICAL_HISTORY;
DELETE FROM DOCTOR;
DELETE FROM TEST_CATALOG;
DELETE FROM NURSE;
DELETE FROM MEDICAL_TEST;
DELETE FROM APPOINTMENT;
DELETE FROM ILLNESS_CATALOG;
DELETE FROM ILLNESS;
DELETE FROM LONG_TERM_ILLNESS;
DELETE FROM MEDICATION_CATALOG;
DELETE FROM PRESCRIPTION;
DELETE FROM DOSE;

SELECT *
FROM PATIENT
SELECT *
FROM MEDICAL_HISTORY
SELECT *
FROM SURGERY
SELECT *
FROM ALLERGY
SELECT * 
FROM DOCTOR;
SELECT * 
FROM TEST_CATALOG;
SELECT * 
FROM NURSE;
SELECT * 
FROM MEDICAL_TEST;
SELECT * 
FROM APPOINTMENT;
SELECT * 
FROM ILLNESS_CATALOG;
SELECT * 
FROM ILLNESS;
SELECT * 
FROM LONG_TERM_ILLNESS;
SELECT * 
FROM MEDICATION_CATALOG;
SELECT * 
FROM PRESCRIPTION;
SELECT * 
FROM DOSE;
SELECT * 
FROM RECOMMENDATION;
SELECT * 
FROM IS_ALLERGIC_TO;

--P2 has multiple allergies, medical tests, appointments, long term illnesses etc
UPDATE PATIENT --cascade update
SET PATIENT_ID = 'P21'
WHERE PATIENT_ID = 'P2';

DELETE FROM PATIENT WHERE PATIENT_ID = 'P21'; --cascade delete

SELECT * --now there is no P2
FROM MEDICAL_HISTORY
WHERE PATIENT_ID = 'P2';
SELECT *
FROM SURGERY
WHERE PATIENT_ID = 'P2';
SELECT *
FROM ALLERGY
WHERE PATIENT_ID = 'P2';
SELECT *
FROM LONG_TERM_ILLNESS
WHERE PATIENT_ID = 'P2';

SELECT * --all P2's are now P21 shows cascade
FROM MEDICAL_HISTORY
WHERE PATIENT_ID = 'P21';
SELECT *
FROM SURGERY
WHERE PATIENT_ID = 'P21';
SELECT *
FROM ALLERGY
WHERE PATIENT_ID = 'P21';
SELECT *
FROM LONG_TERM_ILLNESS
WHERE PATIENT_ID = 'P21';
